name: ruff linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: pip install ruff
    - run: ruff check . #--fix
    #- uses: chartboost/ruff-action@v1
    #  with:
    #    fix_args: --fix
    #  with:
    #    args: --check .
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'style fixes by ruff'
