name: release

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  deploy:
    name: Publish to test PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1 #pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        #user: Hendrik_Code
        verbose: true
        password: ${{ secrets.PYPI_API_TOKEN }}
